package enums.states;

public enum State {
    Q0,
    Q1,
    Q2,
    Q3,
    QY,
    QN,

    Q_ADDITION_Y,
    Q_ADDITION_X_WITH_ZERO,
    Q_ADDITION_X_WITH_ZERO_AND_CARRY,
    Q_ADDITION_X_WITH_ONE_AND_CARRY,
    Q_ADDITION_X_WITH_ONE,

    Q_MULTIPLICATION_Y,
    Q_MULTIPLICATION_X_WITH_ZERO,
    Q_MULTIPLICATION_X_WITH_ONE,
    Q_MULTIPLICATION_RETURN_TO_END_AFTER_MULTIPLYING,

    Q_SUBTRACTION_Y,
    Q_SUBTRACTION_X_WITH_ZERO,
    Q_SUBTRACTION_X_WITH_ZERO_AND_CARRY,
    Q_SUBTRACTION_X_WITH_ONE,
    Q_SUBTRACTION_X_WITH_ONE_AND_CARRY,

    START_ADDITION_OPERATION,
    START_SUBTRACTION_OPERATION,
    START_MULTIPLICATION_OPERATION,
    Q_FIND_DELIMITER_FROM_ZERO,
    Q_FIND_DELIMITER_FROM_ONE,
    Q_RETURN_TO_EQUALS_FROM_OUTPUT,
    Q_SHIFT_ZERO,
    Q_SHIFT_ZERO_AND_ABORT,
    Q_SHIFT_ONE,
    Q_SHIFT_ONE_AND_ABORT,
    Q_CHECK_FOR_LEFT_OVER_BITS,
    Q_CHECK_FOR_LEFT_OVER_BITS_WITH_CARRY,
    Q_CHECK_FOR_CARRY_OTHERWISE_ABORT,

    Q_OUTPUT_WRITE_ZERO,
    Q_OUTPUT_WRITE_ONE,
    Q_OUTPUT_RETURN_TO_EQUALS_WITH_ZERO,
    Q_OUTPUT_RETURN_TO_EQUALS_WITH_ONE,
    Q_OUTPUT_RETURN_TO_EQUALS_WITH_ONE_AND_ABORT,
    Q_OUTPUT_IS_SHIFT_NECESSARY_WITH_ZERO,
    Q_OUTPUT_IS_SHIFT_NECESSARY_WITH_ONE,
    Q_OUTPUT_IS_SHIFT_NECESSARY_WITH_ONE_AND_ABORT,


}
